from pytorch_framework.utils import CustomCfgNode as CN


DEFAULT_CONFIG = CN(visible=False)

DEFAULT_CONFIG.CATEGORY = 'default'
DEFAULT_CONFIG.APPEND_CATEGORY_NAME = False

DEFAULT_CONFIG.GLOBAL_PARAMS = CN(visible=False)
DEFAULT_CONFIG.GLOBAL_PARAMS.task = 'binary'
DEFAULT_CONFIG.GLOBAL_PARAMS.num_classes = 1

DEFAULT_CONFIG.TRAINING = CN(visible=False)

DEFAULT_CONFIG.TRAINING.JaccardIndex = CN(visible=False)
DEFAULT_CONFIG.TRAINING.JaccardIndex.LEVEL = 3
DEFAULT_CONFIG.TRAINING.JaccardIndex.ALIAS = 'IoU'
DEFAULT_CONFIG.TRAINING.Accuracy = CN(visible=False)
DEFAULT_CONFIG.TRAINING.Accuracy.LEVEL = 3

DEFAULT_CONFIG.VALIDATION = CN(visible=False)

DEFAULT_CONFIG.VALIDATION.JaccardIndex = CN(visible=False)
DEFAULT_CONFIG.VALIDATION.JaccardIndex.LEVEL = 2
DEFAULT_CONFIG.VALIDATION.JaccardIndex.ALIAS = 'IoU'
DEFAULT_CONFIG.VALIDATION.Accuracy = CN(visible=False)
DEFAULT_CONFIG.VALIDATION.Accuracy.LEVEL = 2

DEFAULT_CONFIG.TEST = CN(visible=False)

DEFAULT_CONFIG.TEST.Accuracy = CN(visible=False)
DEFAULT_CONFIG.TEST.Accuracy.LEVEL = 2
DEFAULT_CONFIG.TEST.Recall = CN(visible=False)
DEFAULT_CONFIG.TEST.Recall.LEVEL = 2
DEFAULT_CONFIG.TEST.Specificity = CN(visible=False)
DEFAULT_CONFIG.TEST.Specificity.LEVEL = 2
DEFAULT_CONFIG.TEST.Precision = CN(visible=False)
DEFAULT_CONFIG.TEST.Precision.LEVEL = 2
DEFAULT_CONFIG.TEST.F1Score = CN(visible=False)
DEFAULT_CONFIG.TEST.F1Score.LEVEL = 2
DEFAULT_CONFIG.TEST.JaccardIndex = CN(visible=False)
DEFAULT_CONFIG.TEST.JaccardIndex.LEVEL = 2
DEFAULT_CONFIG.TEST.JaccardIndex.ALIAS = 'IoU'
# DEFAULT_CONFIG.TEST.DiceScore = CN(visible=False)
# DEFAULT_CONFIG.TEST.DiceScore.LEVEL = 2
# DEFAULT_CONFIG.TEST.DiceScore.DOMAIN = 'segmentation'